spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/apikeydb
    username: apikey-user
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
